context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Ears Loopback"
            audio.position = [ FL FR ]
            playback.props = {
               stream.dont-remix = true
               node.max-latency = 480/48000
            }
        }
    }
]
