context.modules = [
  {   name = libpipewire-module-echo-cancel
      args = {
          source.props = {
              filter.smart = true
              filter.smart.name = echo-cancel-source
              filter.smart.after = [ capture-merger-source, compressor-source ]
          }
      }
  }
]
