# use a standard location for the status database:
status_path "~/.local/share/pimsync/status/"

storage personal_cal_remote {
  type caldav
  url https://radicale.missbanal.net
  username Erynn_
  password {
   cmd pass tools/radicale/Erynn_
  }
}

storage personal_cal_local {
  type vdir/icalendar
  path ~/.local/share/personal/icalendar/
}

pair personal_cal {
  storage_a personal_cal_local
  storage_b personal_cal_remote
  collections all
}
